#!/bin/bash

component=model-distill-qwen-1-5b-q8-0-gguf
tag="snap.$SNAP_INSTANCE_NAME.$component.hook.install"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

echo "I have been installed!"
