name: example-memory
description: Example stack for legacy CPUs, offering full accuracy but very high memory use
maintainer: Canonical Ltd
devices:
  any:
    - type: cpu
      vendor-id: AuthenticAMD
    - type: cpu
      vendor-id: GenuineIntel
memory: 64G
disk-space: 29G
components:
  - llamacpp
  - model-f32-gguf
