#!/bin/bash

# model-distill-qwen-7b-q4-k-m-gguf

sudo snap set deepseek-r1 model=model-distill-qwen-7b-q4-k-m-gguf
sudo snap set deepseek-r1 engine=llamacpp
sudo snap set deepseek-r1 stack=cpu

# sudo snap set deepseek-r1 model=model-distill-qwen-7b-q4-k-m-gguf
# sudo snap set deepseek-r1 engine=llamacpp-avx512
# sudo snap set deepseek-r1 stack=cpu-avx512
