#!/bin/bash -eu

log_prefix="init:"
log()
{
    echo "$log_prefix $1"
}

base_url=https://models.mistralcdn.com/mistral-7b-v0-3
file=mistral-7B-Instruct-v0.3.tar

cd $SNAP_USER_COMMON

model_dir=model-safetensors

if [ ! -d $model_dir ]; then

    if [ ! -f $file ]; then
        log "Missing model: $file"
        
        # The download can be interrupted and resumed later on
        # Use a temporary name up until the model is fully downloaded
        tmp_file=$file.tmp
        log "Downloading model..."
        wget --quiet --show-progress --continue $base_url/$file --output-document=$tmp_file
        mv $tmp_file $file
    fi

    # Extracting can be interrupted and started over
    # Rename only after success
    log "Extracting archive..."
    rm --force --recursive $model_dir-tmp
    mkdir $model_dir-tmp
    tar --extract --verbose --file $file --directory $model_dir-tmp
    mv $model_dir-tmp $model_dir

    rm $file
fi

export MODEL_DIR=$SNAP_USER_COMMON/$model_dir
