#!/bin/bash -eu

# NPU libraries provided via the npu-libs content interface
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}:$SNAP/npu-libs"

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"

extra_args=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--log_level DEBUG)
fi

set -x
ovms \
    --rest_port "$port" \
    --rest_bind_address "$host" \
    --model_name "$MODEL_NAME" \
    --model_path "$MODEL_PATH" \
    --task text_generation \
    --target_device NPU \
    "${extra_args[@]}" \
    "$@"
