name: intel-npu
description: Stack for inference on Intel NPUs
vendor: Intel Corporation
grade: stable
devices:
  all:
    - type: cpu
      architecture: amd64
  any:    
    # Lunar Lake NPU
    - type: npu
      vendor-id: 0x8086 # Intel Corporation
      device-id: 0x643e 
    # Meteor Lake NPU
    - type: npu
      vendor-id: 0x8086
      device-id: 0x7d1d

memory: 4G
disk-space: 8G
components:
  - &e openvino-model-server
  - &m model-distill-qwen-7b-openvino-int4
configurations:
  engine: *e
  model: *m
  target-device: NPU
