#!/bin/bash -eu

BASE_URL=https://models.mistralcdn.com/mistral-7b-v0-3
FILE=mistral-7B-Instruct-v0.3.tar

cd $SNAP_USER_COMMON

if [ ! -d "model" ]; then

    if [ ! -f "$FILE" ]; then
        echo "Missing model: $FILE"
        
        # The download can be interrupted and resumed later on
        # Use a temporary name up until the model is fully downloaded
        TMP_FILE="$FILE.tmp"
        echo "Downloading model..."
        wget --quiet --show-progress --continue $BASE_URL/$FILE --output-document="$TMP_FILE"
        mv "$TMP_FILE" "$FILE"
    fi

    # Extracting can be interrupted and started over
    # Rename only after success
    echo "Extracting archive..."
    rm --force --recursive model-tmp
    mkdir model-tmp
    tar --extract --verbose --file $FILE --directory model-tmp
    mv model-tmp model

    rm $FILE
fi
