#!/bin/bash -eu

base_url=https://models.mistralcdn.com/mistral-7b-v0-3
file=mistral-7B-Instruct-v0.3.tar

cd $SNAP_USER_COMMON

if [ ! -d "model" ]; then

    if [ ! -f "$file" ]; then
        echo "Missing model: $file"
        
        # The download can be interrupted and resumed later on
        # Use a temporary name up until the model is fully downloaded
        tmp_file="$file.tmp"
        echo "Downloading model..."
        wget --quiet --show-progress --continue $base_url/$file --output-document="$tmp_file"
        mv "$tmp_file" "$file"
    fi

    # Extracting can be interrupted and started over
    # Rename only after success
    echo "Extracting archive..."
    rm --force --recursive model-tmp
    mkdir model-tmp
    tar --extract --verbose --file $file --directory model-tmp
    mv model-tmp model

    rm $file
fi
