#!/bin/bash -eu

ENGINE=$SNAP_COMPONENTS/llamacpp-avx512
MODEL=$SNAP_COMPONENTS/model-q4-k-m-gguf

if [ ! -d $MODEL ]; then
    echo "Missing component: $MODEL"
    exit 1
fi

$MODEL/init
MODEL_FILE=$SNAP_USER_COMMON/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf

if [ ! -d $ENGINE ]; then
    echo "Missing component: $ENGINE"
    exit 1
fi

# For staged shared objects
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ENGINE/usr/lib/$ARCH_TRIPLET:$ENGINE/usr/local/lib

exec $ENGINE/usr/local/bin/llama-cli --conversation --model $MODEL_FILE
