#!/bin/bash -eu

source "$(dirname "$0")/common.sh"

port="$(snapctl get http.port)"
host="$(snapctl get http.host)"

exec "$engine/bin/llama-server" --model "$MODEL_FILE" --port "$port" --host "$host" --threads 40 --threads-batch 40 --no-mmap
