name: ampere-one
description: Optimized for Ampere One CPUs
vendor: Ampere Computing
grade: stable
devices:
  any:
    - type: cpu
      architecture: arm64
      implementer-id: 0xc0 # Ampere Computing
      part-number: 0xac3   # One/Siryn
    - type: cpu
      architecture: arm64
      implementer-id: 0xc0 # Ampere Computing
      part-number: 0xac4   # 1A/OneX/OneM/Banshee
memory: 4G
disk-space: 8G
components:
  - &engine llama-aio-ampereone
  - &model model-distill-qwen-7b-q4-k-m-gguf
configurations:
  engine: *engine
  model: *model
  http.base-path: v1
