#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"
sleep_idle_seconds="$(modelctl get sleep-idle-seconds)"

set -x
# --n-gpu-layers 999 offloads all model layers to the GPU.
# Adding --no-warmup to skip the model warmup phase during server startup in order
# to reduce resource usage if not needed.
exec llama-server \
  --model "$MODEL_FILE" \
  --alias "$MODEL_NAME" \
  --n-gpu-layers 999 \
  --port "$port" \
  --host "$host" \
  --no-warmup \
  --sleep-idle-seconds "$sleep_idle_seconds" \
  "$@"
