#!/bin/bash -eu

source "$(dirname "$0")/common.sh"

port="$($SNAP_NAME get http.port)"
host="$($SNAP_NAME get http.host)"
verbose="$($SNAP_NAME get verbose)"
extra_args=()
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

exec "$server/usr/local/bin/llama-server" --model "$MODEL_FILE" --n-gpu-layers $N_GPU_LAYERS --port "$port" --host "$host" "${extra_args[@]}"
