#!/bin/bash -eu

source "$(dirname "$0")/common.sh"

port="$(deepseek-r1 get http.port)"
host="$(deepseek-r1 get http.host)"
verbose="$(deepseek-r1 get verbose)"
extra_args=()
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

exec "$server/usr/local/bin/llama-server" --model "$MODEL_FILE" --port "$port" --host "$host" "${extra_args[@]}"
