#!/bin/bash -eu

engine=$SNAP_COMPONENTS/mistral-inference
model=$SNAP_COMPONENTS/model

if [ ! -d $model ]; then
    echo "Missing component: $model"
    exit 1
fi

$model/init
model_files=$SNAP_USER_COMMON/model

if [ ! -d $engine ]; then
    echo "Missing component: $engine"
    exit 1
fi

export PYTHONPATH=$engine/lib/python3.12/site-packages

exec $engine/bin/mistral-chat $model_files --instruct --max_tokens=1024
