#!/bin/bash -eu

engine=$SNAP_COMPONENTS/llamacpp
model=$SNAP_COMPONENTS/model-f32-gguf

if [ ! -d $model ]; then
    echo "Missing component: $model"
    exit 1
fi

$model/init
model_file=$SNAP_USER_COMMON/Mistral-7B-Instruct-v0.3-f32.gguf

if [ ! -d $engine ]; then
    echo "Missing component: $engine"
    exit 1
fi

# For staged shared objects
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$engine/usr/lib/$ARCH_TRIPLET

exec $engine/llama-cli --conversation --model $model_file
