#!/bin/bash -eu

ENGINE=$SNAP_COMPONENTS/llamacpp
MODEL=$SNAP_COMPONENTS/model-f32-gguf

if [ ! -d $MODEL ]; then
    echo "Missing component: $MODEL"
    exit 1
fi

$MODEL/init
MODEL_FILE=$SNAP_USER_COMMON/Mistral-7B-Instruct-v0.3-f32.gguf

if [ ! -d $ENGINE ]; then
    echo "Missing component: $ENGINE"
    exit 1
fi

# For staged shared objects
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ENGINE/usr/lib/$ARCH_TRIPLET

exec $ENGINE/llama-cli --conversation --model $MODEL_FILE
