#!/bin/bash -eu

engine=$SNAP_COMPONENTS/llamacpp
model=$SNAP_COMPONENTS/model-f32-gguf

if [ ! -d $model ]; then
    echo "Missing component: $model"
    exit 1
fi

source $model/init

if [ ! -d $engine ]; then
    echo "Missing component: $engine"
    exit 1
fi

# For staged shared objects
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$engine/usr/lib/$ARCH_TRIPLET:$engine/usr/local/lib

exec $engine/usr/local/bin/llama-cli --conversation --model $MODEL_FILE
