name: canonical-2
description: Fallback stack for CPU using llama.cpp engine
maintainer: Canonical Ltd
devices:
  any:
    - type: cpu
      vendor_id: AuthenticAMD
    - type: cpu
      vendor_id: GenuineIntel
memory: 64G
disk_space: 29G
components:
  - llamacpp
  - model-f32-gguf
