name: canonical-1
description: Fallback stack for CPU using llama.cpp engine
maintainer: Canonical Ltd
devices:
  any:
    - type: cpu
      architectures: [amd64]
memory: 8G
disk-space: 5G
components:
  - llamacpp
  - model-q4-k-m-gguf
