#!/bin/bash -eu

component_name=model-q4-k-m-gguf

log_prefix="init:"
log()
{
    echo "$log_prefix $1"
}


model_filename=Mistral-7B-Instruct-v0.3-Q4_K_M.gguf
model_path=$SNAP_COMPONENTS/$component_name/$model_filename

if [ ! -f $model_path ]; then
    log "Model not included in the snap component: $component_name"

    repo_http_url=https://huggingface.co/lmstudio-community/Mistral-7B-Instruct-v0.3-GGUF
    commit=29a785419661afc70b5cd91b5023a835b0092281

    cd $SNAP_USER_COMMON

    if [ ! -f $model_filename ]; then
        log "Model not downloaded."
        
        # The download can be interrupted and resumed later on
        # Use a temporary name up until the model is fully downloaded
        tmp_file=$model_filename.tmp
        log "Downloading model..."
        wget --quiet --show-progress --continue $repo_http_url/resolve/$commit/$model_filename --output-document=$tmp_file
        mv $tmp_file $model_filename
    fi

    model_path=$SNAP_USER_COMMON/$model_filename
    
    log "Using downloaded model: $model_path"
fi

export MODEL_FILE=$model_path
