#!/bin/bash -eu

source "$(dirname "$0")/common.sh"

port="$($SNAP_NAME get http.port)"
host="$($SNAP_NAME get http.host)"
verbose="$($SNAP_NAME get verbose)"
extra_args=()
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

exec "$server/bin/llama-server" --model "$MODEL_FILE" --port "$port" --host "$host" --threads 40 --threads-batch 40 --no-mmap "${extra_args[@]}"
