#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"

extra_args=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

set -x
# --threads/--threads-batch 40 and --no-mmap are tuned for Ampere One CPUs.
# Adding --no-warmup to skip the model warmup phase during server startup in order
# to reduce resource usage if not needed.
exec llama-server \
  --model "$MODEL_FILE" \
  --alias "$MODEL_NAME" \
  --threads 40 \
  --threads-batch 40 \
  --no-mmap \
  --port "$port" \
  --host "$host" \
  --no-warmup \
  "${extra_args[@]}" \
  "$@"
