name: cpu
description: Example stack for legacy CPUs, offering good accuracy with low footprints
vendor: Canonical Ltd
grade: stable
devices:
  any:
    - type: cpu
      architecture: amd64
      flags: [sse4_2, f16c, fma, avx, avx2]
memory: 4G
disk-space: 8G
components:
  - &engine llamacpp
  - &model model-distill-qwen-7b-q4-k-m-gguf
configurations:
  engine: *engine
  model: *model
  http.base-path: v1
