name: example-cpu
description: Example stack for legacy CPUs, offering good accuracy with low footprints
maintainer: Canonical Ltd
devices:
  any:
    - type: cpu
      architectures: [amd64]
      flags:
        - avx
memory: 4G
disk-space: 4G
components:
  - llamacpp
  - model-distill-qwen-q8-gguf
configurations:
  engine: llamacpp
  model: model-distill-qwen-q8-gguf
