name: example-cpu
description: Example stack for legacy CPUs, offering good accuracy with low footprints
maintainer: Canonical Ltd
devices:
  any:
    - type: cpu
      architectures: [amd64]
memory: 8G
disk-space: 5G
components:
  - llamacpp
  - model-q4-k-m-gguf
