name: example-cpu-avx512
description: Example stack for modern CPUs, offering good accuracy with low footprints
maintainer: Canonical Ltd
devices:
  any:
    - type: cpu
      architectures: [amd64]
      flags:
        - avx
        - avx2
        - avx512f
        - avx512dq 
        - avx512bw
memory: 4G
disk-space: 4G
components:
  - llamacpp-avx512
  - model-distill-qwen-q8-gguf
configurations:
  engine: llamacpp-avx512
  model:  model-distill-qwen-q8-gguf
