#!/bin/bash -eu

echo "Error: Not implemented."
echo ""
echo "Start the server and use an OpenAI compliant chat client to connect to it."
echo ""
echo "To run the server in the background, use:"
echo "sudo snap start $SNAP_INSTANCE_NAME.server"
echo ""
echo "To run the server in the foreground, use:"
echo "sudo snap run $SNAP_INSTANCE_NAME.server"

exit 1
