#!/bin/bash -eu

# TODO: should most of this script move to the ovms component?

engine="$SNAP_COMPONENTS/$(snapctl get engine)"
model="$SNAP_COMPONENTS/$(snapctl get model)"

if [ ! -d "$model" ]; then
    echo "Missing component: $model"
    exit 1
fi

source "$model/init" # imports model config

if [ ! -d "$engine" ]; then
    echo "Missing component: $engine"
    exit 1
fi


# Add staged shared objects
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$engine/lib"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$engine/lib/python"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$engine/usr/lib/$ARCH_TRIPLET"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/usr/local/lib"
export LD_LIBRARY_PATH
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

# To find the intel.icd file, containing the path to libigdrcl.so
export OCL_ICD_VENDORS=$SNAP/etc/OpenCL/vendors

# Add Python dependencies
export PYTHONPATH="$engine/lib/python:$engine/lib/python3.12/site-packages"
echo "PYTHONPATH: $PYTHONPATH"

target_device="$(snapctl get target-device)"
if [ -z "$target_device" ]; then
    echo "target-device configuration not set!"
    exit 1
fi

port="$(snapctl get http.port)"
host="$(snapctl get http.host)"

# git and git-lfs are present in the OVMS package but not in path.
# These binaries should not be needed when the model is available locally

# The --source_model and --model_repository_path args are pull-related arguments.
# OVMS does not work when using the alternative --model_name and --model_path arguments.
# Issue TBA

set -x
$engine/bin/ovms \
    --rest_port "$port" \
    --rest_bind_address "$host" \
    --source_model "$MODEL_NAME" \
    --model_repository_path "$model" \
    --target_device "$target_device" \
    --cache_size 2
