name: intel-gpu
description: Stack for inference on Intel Battlemage discrete GPUs
vendor: Intel Corporation
grade: stable
devices:
  all:
    - type: cpu
      architectures: [amd64]
      
    - type: gpu
      bus: pci
      pci-vendor-id: 0x8086 # Intel Corporation
      pci-model-ids:
        - 0xe202 # Battlemage G21 [Intel Graphics]
        - 0xe20b # Battlemage G21 [Arc B580]
        - 0xe20c # Battlemage G21 [Arc B570]
        - 0xe20d # Battlemage G21 [Intel Graphics]
        - 0xe210 # Battlemage G21 [Intel Graphics]
        - 0xe212 # Battlemage G21 [Intel Graphics]
        - 0xe215 # Battlemage G21 [Intel Graphics]
        - 0xe216 # Battlemage G21 [Intel Graphics]
      # vram: 5G
memory: 4G
disk-space: 8G
components:
  - &e openvino-model-server
  - &m model-distill-qwen-7b-openvino-int4
configurations:
  engine: *e
  model: *m
  target-device: GPU
