#!/bin/bash -eu

component_name=model-distill-qwen-q8-gguf

log_prefix="init:"
log()
{
    echo "$log_prefix $1"
}

model_filename=DeepSeek-R1-Distill-Qwen-1.5B-Q8_0.gguf
model_path=$SNAP_COMPONENTS/$component_name/$model_filename

export MODEL_FILE=$model_path
