name: Test snap

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      channel:
        description: 'Snap store channel'
        required: true
        type: string

jobs:
  test:
    name: Test
    strategy:
      # max-parallel: Don't use this as the self-hosted Github runners team wants to see and fix scaling issues.
      # These limits also do not apply to dynamic instances, like the standard self-hosted runners.
      fail-fast: false
      matrix:
        jobs:
          - job_queue: 201909-27366 # Dell - XPS 13 7390 - Italia CML
            expected_stack: cpu-avx512
            expected_tps: 3 # 3.97, 3.35
          - job_queue: 202212-30936 # Ampere Altra
            expected_stack: ampere-altra
            expected_tps: 9 # 10.39
          - job_queue: 202303-31419 # Ampere Altra Max
            expected_stack: ampere-altra
            expected_tps: 18 # 19.86
          - job_queue: 202501-36266
            expected_stack: ampere-one
            expected_tps: 9 # 15.97, 9.93
          - job_queue: hp-zbook-studio-156-inch-g8-mobile-workstation-pc
            select_stack: cuda
            expected_stack: cuda
            expected_tps: 45 # 55.82, 48.41
            install_nvidia_drivers: true
            nvidia_drivers_version: 550
          - job_queue: hp-z4-g4-workstation
            select_stack: cuda
            expected_stack: cuda
            expected_tps: 7 # 14.72, 7.63
            install_nvidia_drivers: true
            nvidia_drivers_version: 550

    runs-on: self-hosted-linux-amd64-jammy-private-endpoint-medium

    env:
      TEST_DIR: test

    steps:
      - name: Event data
        run: |
          echo ::notice::Snap channel:   ${{ inputs.channel }}
          echo ::notice::Job queue:      ${{ matrix.jobs.job_queue }}
          echo ::notice::Expected stack: ${{ matrix.jobs.expected_stack }}
          echo ::notice::Expected TPS:   ${{ matrix.jobs.expected_tps }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add config to testflinger job
        env:
          SNAP_NAME: deepseek-r1
          SNAP_CHANNEL: ${{ inputs.channel }}
          JOB_QUEUE: ${{ matrix.jobs.job_queue }}
          SELECT_STACK: ${{ matrix.jobs.select_stack }}
          EXPECTED_STACK: ${{ matrix.jobs.expected_stack }}
          EXPECTED_TPS: ${{ matrix.jobs.expected_tps }}
          INSTALL_NVIDIA_DRIVERS: ${{ matrix.jobs.install_nvidia_drivers }}
          NVIDIA_DRIVERS_VERSION: ${{ matrix.jobs.nvidia_drivers_version }}

        run: |
          envsubst \
            < $TEST_DIR/testflinger.yaml \
            > $TEST_DIR/testflinger.temp.yaml
          mv $TEST_DIR/testflinger.temp.yaml $TEST_DIR/testflinger.yaml

      - name: Dump job yaml
        run: |
          cat ${{ env.TEST_DIR }}/testflinger.yaml

      - name: Run testflinger job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ env.TEST_DIR }}/testflinger.yaml
