name: Test snap

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      channel:
        description: 'Snap store channel'
        required: true
        type: string

jobs:
  test:
    name: Test
    strategy:
      # Can set max-concurrent / max-parallel, but don't use. Team wants to see/fix scaling. Limits also don't apply to dynamic instances.
      fail-fast: false
      matrix:
        jobs:
#          - job_queue: dell-xps137390-c27366
#            expected_stack: cpu-avx512
#            expected_tps: 3.5 # 3.97
#          - job_queue: 202212-30936 # Ampere Altra
#            expected_stack: ampere-altra
#            expected_tps: 9 # 10.39
#          - job_queue: 202303-31419 # Ampere Altra Max
#            expected_stack: ampere-altra
#            expected_tps: 15 # 19.86
          - job_queue: 202501-36266
            expected_stack: ampere-one
            expected_tps: 80 # 15.97

    runs-on: self-hosted-linux-amd64-jammy-private-endpoint-medium

    env:
      TEST_DIR: test/stack-tps

    steps:
      - name: Event data
        run: |
          echo ::notice::Snap channel:   ${{ inputs.channel }}
          echo ::notice::Job queue:      ${{ matrix.jobs.job_queue }}
          echo ::notice::Expected stack: ${{ matrix.jobs.expected_stack }}
          echo ::notice::Expected TPS:   ${{ matrix.jobs.expected_tps }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Add config to testflinger job
        env:
          SNAP_NAME: deepseek-r1
          SNAP_CHANNEL: ${{ inputs.channel }}
          JOB_QUEUE: ${{ matrix.jobs.job_queue }}
          EXPECTED_STACK: ${{ matrix.jobs.expected_stack }}
          EXPECTED_TPS: ${{ matrix.jobs.expected_tps }}
        run: |
          envsubst \
            < $TEST_DIR/testflinger.yaml \
            > $TEST_DIR/testflinger.temp.yaml
          mv $TEST_DIR/testflinger.temp.yaml $TEST_DIR/testflinger.yaml

      - name: Dump job yaml
        run: |
          cat ${{ env.TEST_DIR }}/testflinger.yaml

      - name: Run testflinger job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ env.TEST_DIR }}/testflinger.yaml
