name: Test snap

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      channel:
        description: 'Snap store channel'
        required: true
        type: string

jobs:
  test:
    name: Test
    strategy:
      # max-parallel: Don't use this as the self-hosted Github runners team wants to see and fix scaling issues.
      # These limits also do not apply to dynamic instances, like the standard self-hosted runners.
      fail-fast: false
      matrix:
        jobs:
          - job_queue: ampere-altra
            expected_engine: ampere-altra
            expected_tps: 9 # Samples: 10.39
          - job_queue: ampere-altra-max
            expected_engine: ampere-altra
            expected_tps: 18 # Samples: 19.86
          - job_queue: ampere-one
            expected_engine: ampere-one
            expected_tps: 9 # Samples: 15.97, 9.93
          - job_queue: docker-nvidia
            expected_engine: cuda
            expected_tps: 10 # Samples: 32.6
            install_nvidia_drivers: true
            nvidia_drivers_version: 550
            select_engine: cuda

    runs-on: self-hosted-linux-amd64-jammy-private-endpoint-medium

    env:
      TEST_DIR: dev/tests/testflinger

    steps:
      - name: Show configuration
        run: |
          # Disable tracing on the runner
          set +x
          
          echo ::notice::Channel: ${{ inputs.channel }}, \
          Queue: ${{ matrix.jobs.job_queue }}, \
          Engine: ${{ matrix.jobs.expected_engine }}, \
          TPS: ${{ matrix.jobs.expected_tps }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Add config to testflinger job
        env:
          SNAP_NAME: deepseek-r1
          SNAP_CHANNEL: ${{ inputs.channel }}
          JOB_QUEUE: ${{ matrix.jobs.job_queue }}
          EXPECTED_ENGINE: ${{ matrix.jobs.expected_engine }}
          EXPECTED_TPS: ${{ matrix.jobs.expected_tps }}
          INSTALL_NVIDIA_DRIVERS: ${{ matrix.jobs.install_nvidia_drivers }}
          NVIDIA_DRIVERS_VERSION: ${{ matrix.jobs.nvidia_drivers_version }}
          SELECT_ENGINE: ${{ matrix.jobs.select_engine }}

        run: |
          envsubst \
            < $TEST_DIR/testflinger.yaml \
            > $TEST_DIR/testflinger.temp.yaml
          mv $TEST_DIR/testflinger.temp.yaml $TEST_DIR/testflinger.yaml

      - name: Print testflinger job
        run: |
          cat ${{ env.TEST_DIR }}/testflinger.yaml

      - name: Run testflinger job
        uses: jpm-canonical/testflinger/.github/actions/submit@action-exit-reasons
        with:
          poll: true
          job-path: ${{ env.TEST_DIR }}/testflinger.yaml
