name: cuda
description: Generic stack for Nvidia GPUs using CUDA. All major CUDA versions are targeted.
vendor: Canonical Ltd
grade: stable
devices:
  all:
    - type: cpu
      architecture: amd64
      flags: [sse4_2, f16c, fma, avx, avx2]
    - type: gpu
      vendor-id: 0x10de # Nvidia Corporation
      vram: 5G
      # compute-capability: 5.0
memory: 4G
disk-space: 8G
components:
  - &engine llamacpp-cuda
  - &model model-distill-qwen-7b-q4-k-m-gguf
configurations:
  engine: *engine
  model: *model
