#!/bin/bash

SNAP_COMPONENTS="/snap/$SNAP_INSTANCE_NAME/components/$SNAP_REVISION" 

# TODO: Detect the suitable stack for mistral-7b-instruct
ENGINE=mistral-inference
snapctl set \
    env.model=mistral-7b-instruct \
    env.engine=$ENGINE \
    env.engine-chat="$ENGINE/bin/chat.py" \
    env.engine-pythonpath="$ENGINE/lib/python3.12/site-packages"